name: belajar_sistem_pajak
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  stroke_text: ^0.0.2
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  youtube_player_flutter: ^9.0.1
  flutter_inappwebview: ^6.0.0
  path_provider: ^2.1.3
  pdf: ^3.10.8
  file_picker: ^8.0.3
  fluttertoast: ^8.2.5
  flutter_to_pdf: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/svg/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
    - family: Schoolbell
      fonts:
        - asset: assets/fonts/Schoolbell-Regular.ttf
          weight: 400
    # - family: Poppins
    #   fonts:
    #     - asset: assets/fonts/Poppins-Medium.ttf
    #       weight: 500